sudo: required

services:
- docker

env:
  matrix:
  - BUILDFOLDER=ranger-admin
  - BUILDFOLDER=ranger-postgres
  global:
  - secure: xWyFXNbFpe2fVCN2JcoXScp1jUmWEs02oHa+MS3AVrgj8MDHiiz+rN1mTsWnMQQLoFtGOXIC4CcpdS0VVK/diCzdt2+fKTpOqwM+xgZSVU7DrJkNE5uc/ZKh+2fy5pwpvAvZS632MN7Xvha1eIreBRciiOXSLHQjpndVtz7lQWU6nU0XrK7i53I0jt5fZbTdSGptWoap0vYrhWg+x1PVCZQGLY7TVKKMlXezlBxD0eubwQBYOh3IRtfRMA5u6OOWyHoqwuiEjXIcPWeehGpDHD5itktD3ajqf8+hIT3tE+EYVb4l45z8RPxk/j/PEOdqcATbTp7fGzIQpNUr/iddiCEllr29NnkwybRPKWzxWc+xPmCPIuDu1r1SNkwrAPID3m6KFImZTunwGO7NtPtvTF43pvqm3yI3SyUpM0Y8w0K65jzR9h+99JUt5blvjAnya3h4ES+jw5JUOl0KrotrhJ3MHihpIMuKMdvvW1yLOgESF6t94CjOTVtv970vPu58rFbMyTgQVqoTrizwSD0OecuRbA0kV7ycH4vzYChZiEhInz60gnDNkNTfjv59TEON9XzYRYMFDpAC3hKPRDkFnmnHjJg7QT8HdU5c+w+QNpv2gK1gLgyRC2CGy2S8hx4fuy8+4nmLRFGJ1tr8Zq3Avjw7fyIgI4jVm2WekhH42sQ=
  - secure: nERQorFRhv/79GLDQcBel17pWY/lvbkbkA1irU+/B+zQBe4BtPLdAe3eclE5zeHmeBYU8tHYFiIprA2UG/R1OqnoL4toLMt8/Z2N98gbD3Ie8PEeeEWcu6e4PQqJieHgPNfE8hRJw4heM07Tsvc+xBnv0uuWS9m65OP2DLuizg2t4dsQ+Vhq2Gk8jQqfAQOtfZU7Xq8H3X4OoJuH1dREqVQJjlEm4Ez1trh5tYk/x0j6ehPa5q6LjFqpKLsXXS3Lj0/JehsZYB0pHIy9D8hm58yGm5fBoZ/RBRfOSo/wZt2IkFjZafBho5J4F5jjdT1HuC28rvxKJ7NOeFqCQJfj9FypRnIuzoASplUiCnvzqJbMwlRofBX/nF5ftxVkNfqCZisNu15j1v24Qcg9hqYm2dw1qmg8uGgL3wtZGaHM0AHIP/bP9B1xQPE3PM+xZ7hzYhOyJ/kKADlaAmk65WOr1+tCcM/owixHAImVhZOm3cnGvjlAzWYWTmzU18nfoxTa49DZv0KpcSXWDR8XrYZFN6s3hhmy77EOAtt0CUG+NO3CIPLNMq0afuKj56wQz/blBkwVayTo7Mf/fLZJRjWRCl9dmHPSZofQyrI2aqg9q/O14GsDx5rcrnmDRglLeOUQ1UFDapMV7NmZeUX0j4pI0EBUWtZ8iW5UOrmhR7i2pDg=

script:
- cd $BUILDFOLDER; 
  echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin; 
  docker pull nielsdenissen/$BUILDFOLDER:latest;
  traviswait docker build --quiet -t nielsdenissen/$BUILDFOLDER:$TRAVIS_BRANCH .;
