version: "2"
services:

  postgres-server:
    build: ./ranger-postgres
    image: nielsdenissen/ranger-postgres
    ports:
      - "5432:5432"
  
  ranger-admin:
    build: ./ranger-admin
    image: nielsdenissen/ranger-admin
    stdin_open: true
    tty: true
    depends_on:
      - "postgres-server"
      - "ceph"
    ports:
      - "6080:6080"

  # Added Ceph to verify the connection of ranger with Ceph for discovering Buckets when creating Policies
  ceph:
    image: ceph/daemon
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
    ports:
      - 8010:8010
    command: demo
